# ======================================================================================================================
# == LICENSE:                 Copyright (c) 2026 Kevin De Coninck.
# == SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
# ======================================================================================================================

# Re-Spot, or rSpot is a highly configurable, static language analyzer.
[package]
name = "rSpot"
version = "1.0.0"
edition = "2024"
